---
- name: "Managing present cron record and ownership manifest"
  ansible.builtin.include_tasks: cron_present_record.yml
  loop: "{{ dovecot_cron_records }}"
  loop_control:
    loop_var: dovecot_cron_present_record
    label: "{{ dovecot_cron_present_record.name | default('invalid') }}"
