---
###############################################################################
#
# uninstall.yml
#
# @author Arsi Atomi
#
###############################################################################

###############################################################################
# ENSURING DOVECOT INSTALLATION AND CONFIGURATION IS ABSENT
###############################################################################

- name: "Ensuring Dovecot installation is absent"
  ansible.builtin.include_tasks: absent.yml
